
let $VIMRUNTIME=$VIM.'/../vimrt'
let $VIMHOME=$VIM . '/../vimfiles'

set packpath=$VIMRUNTIME

set helpfile=$VIMRUNTIME/doc/help.txt

set runtimepath=
set runtimepath+=$VIM/../vimfiles
set runtimepath+=$VIM/../vimrt

let $VIMFILES=$VIM.'/../vimfiles'
so $VIMFILES/vimrc.windows

